[package]
name = "latihan"
version = "0.1.0"
edition = "2021"

[lib]
name = "pokemon"
path = "src/lesson_02_struct/lib.rs"

[dependencies]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

